export const PERMISSION_CODES = {
  USER_READ: 'USER_READ',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  ROLE_READ: 'ROLE_READ',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',
  PERMISSION_READ: 'PERMISSION_READ',
  PERMISSION_CREATE: 'PERMISSION_CREATE',
  PERMISSION_UPDATE: 'PERMISSION_UPDATE',
  PERMISSION_DELETE: 'PERMISSION_DELETE',
  PROJECT_READ: 'PROJECT_READ',
  PROJECT_CREATE: 'PROJECT_CREATE',
  PROJECT_UPDATE: 'PROJECT_UPDATE',
  PROJECT_DELETE: 'PROJECT_DELETE',
  SKILL_READ: 'SKILL_READ',
  SKILL_CREATE: 'SKILL_CREATE',
  SKILL_UPDATE: 'SKILL_UPDATE',
  SKILL_DELETE: 'SKILL_DELETE',
  EXPERIENCE_READ: 'EXPERIENCE_READ',
  EXPERIENCE_CREATE: 'EXPERIENCE_CREATE',
  EXPERIENCE_UPDATE: 'EXPERIENCE_UPDATE',
  EXPERIENCE_DELETE: 'EXPERIENCE_DELETE',
  SITE_SETTING_READ: 'SITE_SETTING_READ',
  SITE_SETTING_UPDATE: 'SITE_SETTING_UPDATE',
  CONTACT_READ: 'CONTACT_READ',
  CONTACT_UPDATE: 'CONTACT_UPDATE',
  CONTACT_DELETE: 'CONTACT_DELETE',
  DASHBOARD_READ: 'DASHBOARD_READ',
  AUDIT_READ: 'AUDIT_READ',
} as const;

export type PermissionCode =
  (typeof PERMISSION_CODES)[keyof typeof PERMISSION_CODES];

export const SUPER_ADMIN_ROLE = 'SUPER_ADMIN';
export const CONTENT_MANAGER_ROLE = 'CONTENT_MANAGER';
